name: shelf_helpers
description: A library with some shelf helpers to not re-invent everything
version: 1.0.0-alpha.0
repository: https://github.com/Kleak/shelf_helpers

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  shelf: ^0.7.9
  pedantic: ^1.9.0

dev_dependencies:
  http: ^0.12.2
