name: shelf_helpers
description: A library with some shelf helpers to not re-invent everything
version: 1.0.0
repository: https://github.com/Kleak/shelf_helpers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.0.0
  pedantic: ^1.9.0

dev_dependencies:
  http: ^0.13.0
  test: ^1.15.7
