name: Test libellule on main

on:
  push:
    branches:
      - main

jobs:
  test_catalog:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
