name: Test libellule on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test_catalog:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed --line-length 80 .

      - name: Analyze project source
        run: dart analyze --fatal-warnings

      - name: Run tests
        run: dart test
